author = "IEDC"
# title = "IEDCMEC"
description = "develop | nurture | sustain"
#copyright = "2020-2021"
profilePicture = "images/global/iedc_logo.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["css/sidebar.css", "css/applause-button.css", "css/author.css"]
# example ["js/custom.js"]
customJs = []
mainSections = ['post']
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3


reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[meta]
title = "IEDCMEC blog"
description = "The official blog of the Innovation and Entrepreneurship Development Cell(IEDC) of Govt. Model Engineering college, Kochi."
metaURL = "https://iedc-blog-git-meta-test-alanphil2k01.vercel.app"
metaImgURL = "https://iedc-blog-git-meta-test-alanphil2k01.vercel.app/images/global/site-feature-image.png"

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"

## Math settings
[math]
enable = false # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/iedcmec/"

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/company/iedcmec/"

[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/iedc_mec"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:iedc@mec.ac.in"

[mermaid]
# enable = true
